apiVersion: v1
kind: Secret
metadata:
  name: safesite-secrets
  namespace: safesite
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://user:password@postgres:5432/safesite_db'
  JWT_SECRET: 'your-super-secret-jwt-key-minimum-32-characters'
